routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
    '/', 'HomeController@index'
);

Route::Group(['middleware'=>'auth'], function () {
    Route::get('l0gslux0d3v12345', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    Route::resource('/food_settings','FoodSettingController');
    Route::group(['middleware' => ['permission:Mengelola Order']], function () {
        Route::get('invoices/print/{order}','InvoiceController@print')->name("invoices.print");
        Route::get('invoices/penagihan/{order}','InvoiceController@tagih')->name("invoices.tagih");

        Route::resource('orders.invoices','InvoiceController');        
        Route::resource('/orders', 'OrderController');
        Route::resource('/invoices', 'InvoiceController');

        Route::get('/invoice/stat','InvoiceController@stat')->name('orders.invoice.stat');
        Route::get('/order/{order}/folios', 'OrderController@folio')->name('orders.folios.index');
        Route::resource('orders.order_documents','OrderDocumentController');
        Route::post('/order/stat','OrderController@stat')->name("orders.stat");
    });

    Route::group(['middleware' => ['permission:Melihat Laporan']], function () {
        Route::resource('/reports','ReportController');
        Route::get('/report/customer', 'ReportController@customer')->name('reports.customer');
        Route::get('/report/facility', 'ReportController@facility')->name('reports.facility');
        Route::get('/report/bkm', 'ReportController@bkm')->name('reports.bkm');
    });

     Route::group(['middleware' => ['permission:Melihat Laporan Penggunaan']], function () {
        Route::get('/usage_index', 'ReportController@usage_index')->name('usages.index');
        Route::get('/report/usage', 'ReportController@usage')->name('reports.usage');
    });

    Route::group(['middleware' => ['permission:Melihat Laporan Penggunaan']], function () {
        Route::get('/report/usage', 'ReportController@usage')->name('reports.usage');
    });

    Route::group(['middleware' => ['permission:Mengelola Jadwal']], function () {
        Route::get('/pint/folio', 'FolioController@print')->name('folios.print');
        Route::resource('/custom_schedules', 'CustomScheduleController');
       Route::resource('/folios', 'FolioController');

    });
    Route::group(['middleware' => ['permission:Mengelola Pengguna']], function () {
        Route::resource('/roles','RoleController');
        Route::resource('/permissions','PermissionController');
        Route::resource('/users', 'UserController');
        Route::get('users/{user}/change_password', 'UserController@change_password_view')->name('users.change_password_view');
        Route::post('users/{user}/change_password_store', 'UserController@change_password_store')->name('users.change_password_store');
   
    });
    Route::group(['middleware' => ['permission:Mengelola Pengaturan Fasilitas']], function () {
        Route::resource('/facility_details', 'FacilityDetailController');
        Route::resource('/facility_attributes', 'FacilityAttributeController');
        Route::resource('/customer_types', 'CustomerTypeController');
        Route::resource('/facility_types', 'FacilityTypeController');
        Route::resource('/categories', 'CategoryController');
        Route::resource('/units', 'UnitController');
        
    });
    Route::group(['middleware' => ['permission:Mengelola Fasilitas']], function () {
        Route::resource('/facilities', 'FacilityController');
        Route::resource('/facilities.galleries', 'FacilityGalleryController');
        Route::resource('/facilities.facility_details', 'FacilityFacilityDetailController');
        Route::resource('/facilities.detail_facilities', 'FacilityDetailFacilityController');
        Route::resource('/facilities.custom_prices', 'FacilityCustomPriceController');
        Route::resource('/detail_facilities.custom_schedules', 'DetailFacilityCustomScheduleController');

    });

    Route::group(['middleware' => ['permission:Mengelola Eduwisata']], function () {
        Route::resource('/education_tours', 'EducationTourController');
        Route::resource('/education_tours.galleries', 'EducationTourGalleryController');
    });
    Route::group(['middleware' => ['permission:Mengelola Berita']], function () {
        Route::resource('/news', 'NewsController');
        Route::get('/news_image/{news}', 'NewsController@editImage')->name('news.editImage');
        Route::put('/news_image/{news}', 'NewsController@updateImage')->name('news.updateImage');
                
    });
    Route::group(['middleware' => ['permission:Mengelola Paket']], function () {
        Route::resource('/bundles.galleries', 'BundleGalleryController');
        Route::resource('/bundles', 'BundleController'); 
        Route::resource('/bundlings', 'BundlingController');
        Route::resource('/bundlings.facilities', 'BundlingFacilityController');
        
    });
    Route::group(['middleware' => ['permission:Mengelola Aktivitas']], function () {
        Route::resource('/activities','ActivtiyController');
        Route::get('/activtiy_image/{activtiy}', 'ActivtiyController@editImage')->name('activities.editImage');
        Route::put('/activtiy_image/{activtiy}', 'ActivtiyController@updateImage')->name('activities.updateImage');
    });
    Route::group(['middleware' => ['permission:Mengelola Fasilitas|Mengelola Tambahan|Mengelola Paket|Mengelola Pengaturan Fasilitas']], function () {
        Route::resource('/custom_prices', 'CustomPriceController')->middleware('permission: Mengelola Fasilitas|Mengelola Pengaturan Fasilitas');
        Route::resource('/special_prices', 'SpecialPriceController')->middleware('permission:Mengelola Fasilitas|Mengelola Tambahan|Mengelola Paket|Mengelola Pengaturan Fasilitas');
    });
    Route::group(['middleware' => ['permission:Mengelola Banner']], function () {
        Route::resource('/banners', 'BannerController');
        Route::resource('/banner_locations','BannerLocationController');
      
    });
    Route::group(['middleware' => ['permission:Mengelola Tambahan']], function () {
        Route::resource('/addons', 'AddonController');
        Route::resource('addons.menus', 'MenuController');
    });
        Route::resource('/customers', 'CustomerController')->middleware('permission:Mengelola Pelanggan');
        Route::resource('/galleries', 'GalleryController')->middleware('permission:Mengelola Galeri');
        // ->middleware('permission:Mengelola Tambahan');

        Route::resource('/coupons', 'CouponController')->middleware('permission:Mengelola Kupon');

        Route::resource('/testimonies', 'TestimonyController')->middleware('permission:Mengelola Testimoni');
    
       
    }
);
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');


Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/order/{id}/invoices/create/{invoice]', 'InvoiceController@create')->name('order.invoice.create.ord');
Route::post('/order/stat','OrderController@stat')->name("orders.stat");

app/Activity.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Activity extends Model
{
    protected $guarded = [];
    
    public function user()
    {
        return $this->BelongsTo('App\User','user_id');
    }

    public function getstatusLabelAttribute()
    {
    $color=["warning","success","danger"];
    $text=["draft","Published","Inactive"];
    return "<span class='label label-".$color[$this->status]."' style='padding:10px'>".$text[$this->status]."</span>";
    }
}

resources/views/activity/_form.blade.php
@extends('layouts.app')

@section('title')
{{ $activity->exists ? 'Ubah' : 'Tambah' }} Aktivitas
@endsection
@if($activity->exists)
@section('actionbtn')
<a data-href="{{ route('activities.destroy', $activity->id) }}" class="btn btn-danger destroy">Hapus Aktivitas</a>
@endsection
@endif
@section('content')

@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-home'></i> Home</a></li>
<li><a href='{{ route("activities.index")}}'><i class='fa fa-compass'></i> Aktivitas</a></li>
<li><a href='#' class='active'>{{ $activity->exists ? 'Ubah' : 'Tambah'}} Aktivitas</a></li>
@endsection

<section class="form-candidate">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-danger">
        <!-- /.box-header -->
        <!-- form start -->
        @if($activity->exists)
        {!! Form::model($activity, ['route' => ['activities.update', $activity->id], 'enctype'=>'multipart/form-data', 'method'=>'PATCH', 'role' => 'form']) !!}
        @else
        {!! Form::model($activity, ['route' => ['activities.store'], 'enctype'=>'multipart/form-data', 'method'=>'POST', 'role' => 'form']) !!}
        @endif
        <div class="box-body">
          <div class="row">
            <div class="form-group col-md-12">
              <label>Judul</label>
              {!! Form::text('title', $activity->title, ['class'=> 'form-control']) !!}
              @if ($errors->has('title'))
              <div class="help-block text-red">
                {{ $errors->first('title') }}
              </div>
              @endif
            </div>
           
            <div class="form-group col-md-12">
              <label>Status</label>
              {!! Form::select('status',['1'=>'Published','2'=>'Inactive'], $activity->active, ['class'=> 'form-control select2']) !!}
              @if ($errors->has('status'))
              <div class="help-block text-red">
                {{ $errors->first('status') }}
              </div>
              @endif
            </div>
            <div class="form-group col-md-12">
              <label>Deskripsi</label>
              {!! Form::textarea('description', $activity->description, ['id'=>'description', 'class'=> 'form-control', 'rows'=>10]) !!}
              @if ($errors->has('description'))
              <div class="help-block text-red">
                {{ $errors->first('description') }}
              </div>
              @endif
            </div>
            <div class="form-group col-md-12">
              {{ Form::label('sort','Prioritas') }}
              {{ Form::number('sort', $activity->sort, ['min'=>0 ,  'placeholder'=>'Masukan Skala Prioritas Tampil',  'class' => 'form-control', 'required']) }}
              @if ($errors->has('sort'))
                <div class="help-block text-red">
                  {{ $errors->first('sort') }}
                </div>
              @endif
            </div>
            
            @if(!$activity->exists)
            <div class="col-md-12">
                {!! Form::file('image', ['id'=>'image', 'class'=> 'form-control',  'onchange'=>'preview_images();']) !!}
            </div>
            <div class="col-md-12">
              <div class="row" id="image_preview">
                <div class='col-md-3' style='padding-top:20px'>
                  @if($activity->exists)
                    <img class='img-responsive' src="{{ asset($activity->image) }}"/>
                  @endif
                </div>
              </div>
            </div>
            @endif

          </div>
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
          <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- CK Editor -->
<script>
</script>
</section>
@endsection
@include('layouts._deletebtn')

@push('scripts')
<script type="text/javascript">
$(document).ready(function() {
  $('.select2').select2();
  function preview_images() {
    $('#image_preview div').html("<img class='img-responsive' src='"+URL.createObjectURL(event.target.files[0])+"'>");
  }
});
</script>
@endpush

resources/views/activity/createImage.blade.php
@extends('layouts.app')

@section('title')
Ubah Gambar
@endsection

@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-home'></i> Home</a></li>
<li><a href='{{ route("activities.index")}}'><i class='fa fa-compass'></i> Aktivitas</a></li>
<li><a href='#' class='active'>Ubah Gambar</a></li>
@endsection
@section('content')

<section class="form-candidate">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-danger">
        <!-- /.box-header -->
        <!-- form start -->
        {!! Form::model($activtiy, ['route' => ['activities.updateImage', $activtiy->id], 'method'=>'put', 'enctype'=>'multipart/form-data','role' => 'form']) !!}
        <div class="box-body">
          <div class="row">

            <div class="form-group col-md-12">
              <label>Image</label>
              {!! Form::file('image', ['class'=> 'form-control', 'required' => 'required']) !!}
            </div>
          </div>
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
          <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
      </form>
    </div>
  </div>
</div>
</section>
@endsection
@include('layouts._deletebtn')

resources/views/activity/index.blade.php
@extends('layouts.app')

@section('title')
Manage Aktivitas
@endsection
@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-home'></i> Home</a></li>
<li><a href='#' class='active'><i class='fa fa-compass'></i> Aktivitas</a></li>
@endsection
@section('content')

<div class="row">
	<!-- Search User -->
	<form method="get" id="search-form">
		<div class="col-md-3">
			<div class="input-group no-border">
				<input type="text" class="form-control column-filter" name="filter[title]" placeholder="Judul" value="{{ !empty($filter['title']) ? $filter['title'] : '' }}"/>
				<span class="input-group-addon icon-search"><i class="fa fa-search"></i></span>
			</div>
		</div>
		<div class="col-md-3">
			<div class="input-group no-border">
				<select name="filter[status]" class="form-control column-filter">
					<option value="" {{ empty($filter['status']) ? 'selected' : '' }}>All</option>
					<option value="1" {{ !empty($filter['status']) && $filter['status'] == 1 ? 'selected' : '' }}>Publish</option>
					<option value="2" {{ !empty($filter['status']) && $filter['status'] == 2 ? 'selected' : '' }}>Inactive</option>
				</select>
				<span class="input-group-addon icon-search"><i class="fa fa-search"></i></span>
			</div>
		</div>
		<div class="col-md-3">
			<button type="submit" class="btn btn-primary btn-block">Cari</button>
		</div>
	</form>
</div>
<br>
<div class="box">
	<div class="box-header">
		<div class="row">
			<div class="col-md-3">
				<a href="{{ route('activities.create')}}" class="btn btn-success btn-block">Tambah Aktivitas &nbsp;<span class="fa fa-plus-circle"></span></a>
			</div>
		</div>
	</div>

	<!-- /.box-header -->
	<div class="box-body">
		<table id="example1" class="table table-bordered table-striped">
			<thead>
				<tr>
					<th>ID</th>
					<th>Judul</th>
					<th>Gambar</th>
					<th>Status</th>
					<th>Edit</th>
					<th>Show</th>
				</tr>
			</thead>
			<tbody>
				@foreach($activitys as $a)
				<tr>
					<td>{{$loop->iteration}}</td>
					<td>{{$a->title}}</td>
					
					<td><img src="{{asset('image/')}}/{{ $a->image ? $a->image : ENV('PLACEHOLDER_IMG','Na.jpg')  }}"  width="60px" height="40px"></td>
					<td>{!! $a->statusLabel !!}</td>
					<td>
						<a href="{{route('activities.edit',$a->id)}}">
							<button class="btn btn-warning">
								Edit
							</button>
						</a>
					</td>
					<td>
						<a href="{{route('activities.show',$a->id)}}">
							<button class="btn btn-primary">
								Show
							</button>
						</a>
					</td>
				</tr>
				@endforeach
					@if($activitys->count() == 0)
					<tr>
					<td colspan="7"><center><em>Tidak Ada Data.</em></center></td>
					</tr>
				@endif
			</tbody>
		</table>
		@php
		$filters = [];
		foreach ($filter as $key => $value) {
		$filters['filter['. $key .']'] = $value;
	}
	@endphp
	{{ $activitys->appends($filters)->links() }}
</div>
</div>

@stop

resources/views/activity/show.blade.php
@extends('layouts.app')
@section('title')
Manage activities
@endsection
@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-home'></i> Home</a></li>
<li><a href='{{ route("activities.index")}}' class='active'><i class='fa fa-compass'></i> Aktivitas</a></li>
<li><a href='#' class='active'>Detail Aktivitas</a></li>
@endsection
@section('content')
<div class="row">
	<section class="col-md-8">
		<div class="box">
			<div class="box-header">
				<div class="row">
					<div class="col-md-12">
						<h1>{{$activity->title}}</h1>
					</div>
				</div>
			</div>	
		</div>
	</section>

	<section class="col-md-4">
		<div class="box">
			<div class="box-header">
				<div class="row">
					<div class="col-md-12">
						<h2>Publisher: {{$activity->user->name}}</h2>
					</div>
				</div>
			</div>	
		</div>
	</section><section class="col-md-12">
		<div class="box">
			
			<div class="box-header">
				<div class="row">
					<div class="col-md-3">
						Image
					</div>
				</div>
			</div>	
			<div class="box-body" style="height: 400px;overflow-y:visible" >
				<div class="row">
					<div class="col-md-12">
						<center>
						<img src="{{asset('image/')}}/{{ $activity->image ? $activity->image : ENV('PLACEHOLDER_IMG','Na.jpg')  }}" width="550px">
						</center>
					</div>
				</div>
			</div>
			<div class="box-footer">
				<div class="row">
					<div class="col-md-3 col-md-offset-9">
						<a href="{{ route('activities.editImage',$activity->id)}}" class="btn btn-warning btn-block">Ubah Gambar &nbsp;<span class="fa fa-plus-circle"></span></a>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="col-md-12">
		<div class="box">
			
			<div class="box-header">
				<div class="row">
					<div class="col-md-3">
						Deskripsi
					</div>
				</div>
			</div>	
			<div class="box-body" style="height: 400px;overflow-y:visible" >
				<div class="row">
					<div class="col-md-12">
						{{ ($activity->description) }}
					</div>
				</div>
			</div>
			<div class="box-footer">
				<div class="row">
					<div class="col-md-3 col-md-offset-9">
						<a href="{{ route('activities.edit',$activity->id)}}" class="btn btn-warning btn-block">Ubah Aktivitas &nbsp;<span class="fa fa-plus-circle"></span></a>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>
@stop