routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
    '/', 'HomeController@index'
);

Route::Group(['middleware'=>'auth'], function () {
    Route::get('l0gslux0d3v12345', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    Route::resource('/food_settings','FoodSettingController');
    Route::group(['middleware' => ['permission:Mengelola Order']], function () {
        Route::get('invoices/print/{order}','InvoiceController@print')->name("invoices.print");
        Route::get('invoices/penagihan/{order}','InvoiceController@tagih')->name("invoices.tagih");

        Route::resource('orders.invoices','InvoiceController');        
        Route::resource('/orders', 'OrderController');
        Route::resource('/invoices', 'InvoiceController');

        Route::get('/invoice/stat','InvoiceController@stat')->name('orders.invoice.stat');
        Route::get('/order/{order}/folios', 'OrderController@folio')->name('orders.folios.index');
        Route::resource('orders.order_documents','OrderDocumentController');
        Route::post('/order/stat','OrderController@stat')->name("orders.stat");
    });

    Route::group(['middleware' => ['permission:Melihat Laporan']], function () {
        Route::resource('/reports','ReportController');
        Route::get('/report/customer', 'ReportController@customer')->name('reports.customer');
        Route::get('/report/facility', 'ReportController@facility')->name('reports.facility');
        Route::get('/report/bkm', 'ReportController@bkm')->name('reports.bkm');
    });

     Route::group(['middleware' => ['permission:Melihat Laporan Penggunaan']], function () {
        Route::get('/usage_index', 'ReportController@usage_index')->name('usages.index');
        Route::get('/report/usage', 'ReportController@usage')->name('reports.usage');
    });

    Route::group(['middleware' => ['permission:Melihat Laporan Penggunaan']], function () {
        Route::get('/report/usage', 'ReportController@usage')->name('reports.usage');
    });

    Route::group(['middleware' => ['permission:Mengelola Jadwal']], function () {
        Route::get('/pint/folio', 'FolioController@print')->name('folios.print');
        Route::resource('/custom_schedules', 'CustomScheduleController');
       Route::resource('/folios', 'FolioController');

    });
    Route::group(['middleware' => ['permission:Mengelola Pengguna']], function () {
        Route::resource('/roles','RoleController');
        Route::resource('/permissions','PermissionController');
        Route::resource('/users', 'UserController');
        Route::get('users/{user}/change_password', 'UserController@change_password_view')->name('users.change_password_view');
        Route::post('users/{user}/change_password_store', 'UserController@change_password_store')->name('users.change_password_store');
   
    });
    Route::group(['middleware' => ['permission:Mengelola Pengaturan Fasilitas']], function () {
        Route::resource('/facility_details', 'FacilityDetailController');
        Route::resource('/facility_attributes', 'FacilityAttributeController');
        Route::resource('/customer_types', 'CustomerTypeController');
        Route::resource('/facility_types', 'FacilityTypeController');
        Route::resource('/categories', 'CategoryController');
        Route::resource('/units', 'UnitController');
        
    });
    Route::group(['middleware' => ['permission:Mengelola Fasilitas']], function () {
        Route::resource('/facilities', 'FacilityController');
        Route::resource('/facilities.galleries', 'FacilityGalleryController');
        Route::resource('/facilities.facility_details', 'FacilityFacilityDetailController');
        Route::resource('/facilities.detail_facilities', 'FacilityDetailFacilityController');
        Route::resource('/facilities.custom_prices', 'FacilityCustomPriceController');
        Route::resource('/detail_facilities.custom_schedules', 'DetailFacilityCustomScheduleController');

    });

    Route::group(['middleware' => ['permission:Mengelola Eduwisata']], function () {
        Route::resource('/education_tours', 'EducationTourController');
        Route::resource('/education_tours.galleries', 'EducationTourGalleryController');
    });
    Route::group(['middleware' => ['permission:Mengelola Berita']], function () {
        Route::resource('/news', 'NewsController');
        Route::get('/news_image/{news}', 'NewsController@editImage')->name('news.editImage');
        Route::put('/news_image/{news}', 'NewsController@updateImage')->name('news.updateImage');
                
    });
    Route::group(['middleware' => ['permission:Mengelola Paket']], function () {
        Route::resource('/bundles.galleries', 'BundleGalleryController');
        Route::resource('/bundles', 'BundleController'); 
        Route::resource('/bundlings', 'BundlingController');
        Route::resource('/bundlings.facilities', 'BundlingFacilityController');
        
    });
    Route::group(['middleware' => ['permission:Mengelola Aktivitas']], function () {
        Route::resource('/activities','ActivtiyController');
        Route::get('/activtiy_image/{activtiy}', 'ActivtiyController@editImage')->name('activities.editImage');
        Route::put('/activtiy_image/{activtiy}', 'ActivtiyController@updateImage')->name('activities.updateImage');
    });
    Route::group(['middleware' => ['permission:Mengelola Fasilitas|Mengelola Tambahan|Mengelola Paket|Mengelola Pengaturan Fasilitas']], function () {
        Route::resource('/custom_prices', 'CustomPriceController')->middleware('permission: Mengelola Fasilitas|Mengelola Pengaturan Fasilitas');
        Route::resource('/special_prices', 'SpecialPriceController')->middleware('permission:Mengelola Fasilitas|Mengelola Tambahan|Mengelola Paket|Mengelola Pengaturan Fasilitas');
    });
    Route::group(['middleware' => ['permission:Mengelola Banner']], function () {
        Route::resource('/banners', 'BannerController');
        Route::resource('/banner_locations','BannerLocationController');
      
    });
    Route::group(['middleware' => ['permission:Mengelola Tambahan']], function () {
        Route::resource('/addons', 'AddonController');
        Route::resource('addons.menus', 'MenuController');
    });
        Route::resource('/customers', 'CustomerController')->middleware('permission:Mengelola Pelanggan');
        Route::resource('/galleries', 'GalleryController')->middleware('permission:Mengelola Galeri');
        // ->middleware('permission:Mengelola Tambahan');

        Route::resource('/coupons', 'CouponController')->middleware('permission:Mengelola Kupon');

        Route::resource('/testimonies', 'TestimonyController')->middleware('permission:Mengelola Testimoni');
    
       
    }
);
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');


Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/order/{id}/invoices/create/{invoice]', 'InvoiceController@create')->name('order.invoice.create.ord');
Route::post('/order/stat','OrderController@stat')->name("orders.stat");

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;

//Importing laravel-permission models
use App\User;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
 use DB; 
 use Illuminate\Validation\ValidationException; 
 use Illuminate\Support\Facades\Validator;

 
class RoleController extends Controller
{
    public function index(Request $request)
    {
        $roles = Role::query();
        $filter = [];
        if(isset($request->filter)) {
            $filter = $request->filter;
            foreach ($filter as $key => $value) {
                if(!empty($value)) {
                    $roles  = $roles->whereRaw("CAST($key as TEXT) ilike '%" . strtolower($value) . "%'");  
                }
            }
        }
        $roles=$roles->orderBy('id','DESC')->paginate(30);
        return view('role.index')
        ->with('roles', $roles)
        ->with('filter',$filter);
    }
    public function create(){
        $role = new Role;
        $permissions = Permission::all()->pluck('name','name');
        return view('role._form')
        ->with('permissions', $permissions)
        ->with('role', $role);
    }
    public function store(Request $request){
        DB::beginTransaction();
        
        $role = new Role;
        $check = Role::orderBy('id','DESC')->first();
                        if($check)
                            $role->id = $check->id+1;
        $role->fill($request->except('permissions'));
        $role->save();
        if (!empty($request->permissions)) {        
            $role->syncPermissions($request->permissions);
        }   
        DB::commit();
        $request->session()->flash('toast', 'Jabatan berhasil ditambahkan!');
        return redirect()->route('roles.index');
    }
    public function edit($id){
        $role = Role::find($id);
        $permissions = Permission::all()->pluck('name','name');

        return view('role._form')
        ->with('permissions', $permissions)
        ->with('role',$role);
    }
    public function update($id, Request $request){
        DB::beginTransaction();
        $role = Role::find($id);
        $role->fill($request->except('permissions'));
        $role->save();
        if (!empty($request->permissions)) {        
            $role->syncPermissions($request->permissions);
        }        
        else {
            $role->permissions()->detach();
        }
        DB::commit();
        $request->session()->flash('toast', 'Jabatan  berhasil diubah!');
        return redirect()->route('roles.index');
    }
    public function show(Role $role){
        return view('role.show')->with('role', $role);
    }
    public function destroy(Request $request, Role $role){
        $role->delete();
        $request->session()->flash('toast', 'Jabatan berhasil dihapus!');
        return redirect()->route('roles.index');
    }
}

resources/views/role/_form.blade.php
@extends('layouts.app')
@section('title')
{{ $role->exists ? 'Ubah' : 'Tambah' }} Jabatan
@endsection
@if($role->exists)
@section('actionbtn')
<a data-href="{{ route('roles.destroy', $role->id) }}" class="btn btn-danger destroy">Hapus Jabatan</a>
@endsection
@endif
@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-dashboard'></i> Home</a></li>
<li><a href='{{ route("roles.index")}}'><i class='fa fa-briefcase'></i> Jabatan</a></li>
<li><a href='#' class='active'>{{ $role->exists ? 'Ubah' : 'Tambah'}} Jabatan</a></li>

@endsection

@section('content')
<div class="row">
    <div class="col-xs-10">
        <div class="box">
            <div class="box-body">
                @if($role->exists)
                    {!! Form::model($role, ['route' => ['roles.update', $role->id], 'method'=>'PATCH', 'files' => true]) !!}
                @else
                    {!! Form::model($role, ['route' => ['roles.store'], 'class' => 'col s12', 'files' => true]) !!}
                @endif
                <div class="form-group col-md-12">
                    {{ Form::label('name','Jabatan') }}
                    {{ Form::text('name', $role->name, [  'placeholder'=>'Masukan Jabatan',  'class' => 'form-control', 'required']) }}
                    @if ($errors->has('name'))
                        <div class="help-block text-red">
                            {{ $errors->first('name') }}
                        </div>
                    @endif
                </div>
                
                <div class="form-group col-md-12">
                    {!! Form::label('permissions[]', 'Hak Akses'); !!}
                    {!! Form::select('permissions[]',$permissions, $role->permissions()->pluck('name'), ['multiple'=>'multiple', 'class' => 'form-control permission', 'style'=>'border:0px none;']) !!}
                </div>

                <div class="box-footer">
                    {{ Form::submit('Save', ['class' => 'btn btn-success']) }}
                </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
<form id='destroy-form' method="POST">
    {{ csrf_field() }}
    <input type="hidden" name="_method" value="DELETE">
</form>
<script type="text/javascript">
    $(document).ready(function() {
        $('.destroy').click(function() {
            if(confirm('Apakah anda yakin?') ) {
                $('#destroy-form').attr('action',$(this).data('href'));
                $('#destroy-form').submit();
            }
        });
        $('.permission').select2({
            'width': '100%',
             placeholder: "Pilih Hak Akses",
        });
    });
</script>
@endpush

resources/views/role/index.blade.php
@extends('layouts.app')
@section('title')
List Jabatan
@endsection
@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-dashboard'></i> Home</a></li>
<li><a href='#' class='active'><i class='fa fa-briefcase'></i>Jabatan</a></li>

@endsection

@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="box box-danger">
            <div class="box-header">
                <a href="{{ route('roles.create') }}"><button class="btn btn-primary"><span>  <i class="fa fa-plus"></i> </span>Tambah Jabatan</button></a>
            </div>
            <div class="box-body">
                <table id="example" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th width="5%">No</th>
                            <th width="25%">Jabatan</th>
                            <th width="15%" colspan="3">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach( $roles as $key => $role )
                        <tr height="10">
                            <td>{{ $key+1 }}</td>
                            <td>{{ $role->name }}</td>
                            <td><a href="{{ route('roles.show',['id'=>$role->id]) }}" class="btn btn-primary btn-block">Show</a></td>
                            <td> <a href="{{ route('roles.edit',['id'=>$role->id]) }}" class="btn btn-warning btn-block">
                                   Edit
                                </a></td>
                        </tr>
                    @endforeach
                    @if($roles->count() == 0)
                        <tr>
                            <td colspan="7"><center><em>Tidak Ada Data.</em></center></td>
                        </tr>
                    @endif
                    </tbody>
            </table>
        </div>
        {{ $roles->links() }}
        </div>
    </div>
</div>
@endsection
@push('scripts')
<form id='destroy-form' method="POST">
    {{ csrf_field() }}
    <input type="hidden" name="_method" value="DELETE">
</form>
<script>
    $(document).ready(function() {
        $('.destroy').click(function() {
            if(confirm('Apakah anda yakin?') ) {
                $('#destroy-form').attr('action',$(this).data('href'));
                $('#destroy-form').submit();
            }
        });
    });
</script>
@endpush

resources/views/role/show.blade.php
@extends('layouts.app')

@section('title')
Detail Jabatan
@endsection

@section('actionbtn')
  <a href="{{ route('roles.edit', $role->id) }}" class="btn btn-warning">Edit</a>
  <a data-href="{{ route('roles.destroy', $role->id) }}" class="btn btn-danger destroy">Hapus</a>
@endsection

@push('styles')
<style type="text/css">

</style>
@endpush

@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-dashboard'></i> Home</a></li>
<li><a href='{{ route("roles.index")}}'><i class='fa fa-briefcase'></i> Jabatan</a></li>

<li><a href='#' class='active'>Detail Jabatan</a></li>
@endsection
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="box box-default">
            <div class="box-body">
                <div class="row">
                    <div class="col-md-12">
                        <label>Nama</label>
                        <h4>{{ $role->name }}</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box box-default">
            <div class="box-body">

        <table class="table dataTable">
            <thead>
              <tr>
                <th class="align-middle">No</th>
                <th class="align-middle">Permission</th>
              </tr>
            </thead>
            <tbody>

              @foreach($role->permissions as $permission)
              <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $permission->name }}</td>
              </tr>
              @endforeach
              @if($role->permissions()->count() == 0)
              <tr>
                <td colspan="12"><center><em>Tidak Ada Data.</em></center></td>
              </tr>
              @endif
            </tbody>
        </table>
            </div>
        </div>
    </div>
</div>

@endsection
@push('scripts')
<form id='destroy-form' method="POST">
    {{ csrf_field() }}
    <input type="hidden" name="_method" value="DELETE">
</form>
<script type="text/javascript">
    $(document).ready(function() {
        $('.destroy').click(function() {
            if(confirm('Apakah anda yakin?') ) {
                $('#destroy-form').attr('action',$(this).data('href'));
                $('#destroy-form').submit();
            }
        });
    });
</script>
@endpush